### ISSUE TITLE
Remark

### ISSUE THREAD

**Issue by Ali3377** [SajadKazemi/parsimatn#1]
These letters س، ش، ص، ض، ف will become better if the Harakat above them are similar to that in your previous fonts (Parsian font).
Note: I mean when it come in the end of the word.
 الشَّمْسً، السَّيْفُ

well done!

**Comment by SajadKazemi** [comment]
Hi.
Thanks for your suggestion.

In [Parsi Matn v1.1](https://github.com/SajadKazemi/parsimatn/releases/tag/v1.1), mark positioning is improved for lots of letters, including the ones you mentioned in the issue.

**Comment by Ali3377** [comment]
Your work is absolutely perfect!
all the best, Dear Sajad
